config/routes.rb
Rails.application.routes.draw do
  get '/articles' => 'articles#index'
  get '/articles/new' => 'articles#new', as: 'new_article'
  post '/articles' => 'articles#create', as: 'create_article'
  get '/articles/:id' => 'articles#show', as: 'article'
  get '/articles/:id/edit' => 'articles#edit', as: 'edit_article' 
  patch '/articles/:id' => 'articles#update'
  delete '/articles/:id' => 'articles#destroy', as: 'delete_article'
end       

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :name, presence: true,
                     uniqueness: true
    validates :body, presence: true,
                     length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: %i[ show edit update destroy ]
    def index
        @articles = Article.all
    end

    def show
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)

        if @article.save
            redirect_to articles_path
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit

    end
    
    def update
        respond_to do |format|
            if @article.update(article_params)
                format.html { redirect_to article_url(@article), notice: "Article was sucessfully updated" }
                format.json { render :show, status: :ok, location: @article }
            else
                format.html { render :edit, status: :unprocessable_entity }
                format.json { render json: @article.errors, status: :unprocessable_entity }
            end
        end
    end

    # def delete
    #     @article.destroy

    #     respond_to do |format|
    #         format.html { redirect_to articles_index_url, notice: "Article was successfully destroyed."}
    #         format.json { head :no_content }
    #     end
    # end

    def destroy
        @article = Article.find(params["id"])
        @article.destroy
        redirect_to articles_path
    end

    private

    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:name, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Name:</strong>
    <%= article.name %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= article.body %>
  </p>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
        <% if article.errors.any? %>
            <div>
                <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved: </h2>
                <ul>
                    <% article.errors.each do |error| %>
                    <li><%= error.full_messages %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>
  <div class="row mb-3">
    <label class=" col-form-label"><%= form.label :Name %></label>
    <div>
    <%= form.text_field :name, class: 'form-control', placeholder: "Name" %>
    </div>
  </div>

  <div class="row mb-3">
    <label class=" col-form-label"><%= form.label :body%></label>
    <div>
    <%= form.text_area :body, class: 'form-control rows-4', placeholder: "Body"  %>
    </div>
  </div>

<div>
    <%= form.submit class: 'btn btn-secondary' %>
</div>

<% end %>

app/views/articles/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark text-light" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to 'Articles', articles_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render "form", article: @article %>

<br>

<div>
    <%= link_to "Back", articles_path, class: 'btn btn-dark' %>
</div>

app/views/articles/index.html.erb
<%= link_to "New Article", new_article_path, class: 'btn btn-secondary' %>
<br/><br/>
<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
     <tr>
        <th>Name</th>
        <th>Body</th>
        <th> </th> 
        <th>Options</th> 
        <th> </th>        
    </tr>
  </thead>

<tbody>
    <% @articles.each do |article| %>
    <tr>
        <td><%= article.name%></td>
        <td><%= article.body%></td>
        <td><%= link_to "View", article, class: 'btn btn-primary' %></td>
        <td><%= link_to "Edit", edit_article_path(article), class: 'btn btn-dark' %></td>
        <td><%= button_to "Delete", delete_article_path(article), method: :delete, confirm: "Are you sure?", class: 'btn btn-danger' %></td>
    </tr>

    <% end %>
</tbody>
</table>

app/views/articles/new.html.erb
  <div class="card" style="width: 20rem;">
    <h4 class="card-header">New Article</h4>
     <div class="card-body">
     
<%= render "form", article: @article %>

app/views/articles/show.html.erb
<div class="card" style="width: 20rem;">
    <h4 class="card-header">Article</h4>
     <div class="card-body">
<%= render @article %>

<div>
    <!--     <%= link_to "Edit this article", edit_article_path(@article), class: 'btn btn-secondary' %>
    <br/>    <br>
        <%= button_to "Delete", delete_article_path, method: :delete, confirm: "Are you sure?", class: 'btn btn-danger' %> -->
    <br/>
    <%= link_to "Back", articles_path, class: 'btn btn-dark' %>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Friends App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'articles/header' %>
    <div class="container">
      <br/>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <br/>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>